comment: false

ignore:
  - "src/json.h"
  - "src/simcm.cpp"
  - "src/muParser*.cpp"
  - "src/muParser*.h"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true