comment: false

ignore:
  - "src/json.h"
  - "src/simcm.cpp"
  - "src/muParser*.cpp"
  - "src/helpers.cpp"
  - "src/muParser*.h"
  - "R/helpers.R"
  - "R/validators.R"
  - "R/distribution.R"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true